### ISSUE TITLE
Infinite rewards with mysql

### ISSUE THREAD

**Issue by liquidman228** [Revivalo/DailyRewards#10]
Hey

I just set up the plugin to use mysql database, but when the player claim a reward, it does not get a cooldown, meaning he can just "spam-claim" the reward
Im using version 1.6.7 and server paper 1.19.3

If more info needed, let me know

**Comment by Revivalo** [comment]
Did you tried the latest version?

**Comment by liquidman228** [comment]
> Did you tried the latest version?

Just tried right now. The /rewards command now does nothing, but in console i get this:

[18:47:46 INFO]: L1quid_man issued server command: /rewards
[18:47:46 WARN]: [DailyRewards] Task #1740 for DailyRewards v1.7.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
        at dev.revivalo.dailyrewards.user.User.getCooldownOfReward(User.java:22) ~[DailyReward-1.7.1.jar:?]
        at dev.revivalo.dailyrewards.managers.MenuManager.lambda$openRewardsMenu$1(MenuManager.java:44) ~[DailyReward-1.7.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by liquidman228** [comment]
> Than delete userdata folder and try it again.

Same. Here is what i get when try /reward claim daily:

[21:04:49 INFO]: L1quid_man issued server command: /reward claim daily
[21:04:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'reward' in plugin DailyRewards v1.7.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-425]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
        at dev.revivalo.dailyrewards.user.User.getCooldownOfReward(User.java:22) ~[DailyReward-1.7.1.jar:?]
        at dev.revivalo.dailyrewards.managers.reward.RewardManager.claim(RewardManager.java:62) ~[DailyReward-1.7.1.jar:?]
        at dev.revivalo.dailyrewards.commandmanager.subcommands.ClaimCommand.perform(ClaimCommand.java:56) ~[DailyReward-1.7.1.jar:?]
        at dev.revivalo.dailyrewards.commandmanager.MainCommand.onCommand(MainCommand.java:39) ~[DailyReward-1.7.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by Revivalo** [comment]
Did you stopped the server, deleted the userdata folder and start it again?

**Comment by liquidman228** [comment]
> Did you stopped the server, deleted the userdata folder and start it again?

Yes. Here is the plugin folder
![image](https://user-images.githubusercontent.com/93479046/234132619-83f9bc3f-72e5-46cc-9e9e-06e079752928.png)
