### ISSUE TITLE
[Bug?] MySQL Error when load server

### ISSUE THREAD

**Issue by Yurinann** [Revivalo/DailyRewards#5]
```
[16:28:13 ERROR]: Error occurred while enabling DailyRewards v1.5.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cz.revivalo.dailyrewards.managers.database.MySQLManager.init(MySQLManager.java:29) ~[?:?]
        at cz.revivalo.dailyrewards.DailyRewards.onEnable(DailyRewards.java:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:505) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:430) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:388) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:728) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:168) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:112) ~[?:?]
        at com.tchristofferson.configupdater.ConfigUpdater.update(ConfigUpdater.java:34) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.YamlFile.<init>(YamlFile.java:35) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Lang.reload(Lang.java:70) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Config.reload(Config.java:88) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Config.<clinit>(Config.java:63) ~[?:?]
        ... 13 more
```

Platform: ImanitySpigot 1.8, Java 17

**Comment by Revivalo** [comment]
Did you build the project or downloaded from MEGA as plugin itself?

**Comment by Yurinann** [comment]
i download in mega



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 9, 2023 06:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Revivalo/DailyRewards] [Bug?] MySQL Error when load server(Issue #5)




 
Did you build the project or downloaded from MEGA as plugin itself?

**Comment by Revivalo** [comment]
There was uploaded an invalid version, now it should be working without problem (https://mega.nz/folder/AEB3SZwI#r8KX4i37tjcqIrFKYnQP7w).

**Comment by Yurinann** [comment]
```
[20:00:57 ERROR]: Error occurred while enabling DailyRewards v1.5.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at cz.revivalo.dailyrewards.managers.database.MySQLManager.init(MySQLManager.java:29) ~[?:?]
        at cz.revivalo.dailyrewards.DailyRewards.onEnable(DailyRewards.java:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:505) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:430) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:388) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:728) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:168) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:112) ~[?:?]
        at com.tchristofferson.configupdater.ConfigUpdater.update(ConfigUpdater.java:34) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.YamlFile.<init>(YamlFile.java:35) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Lang.reload(Lang.java:71) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Config.reload(Config.java:88) ~[?:?]
        at cz.revivalo.dailyrewards.configuration.enums.Config.<clinit>(Config.java:63) ~[?:?]
        ... 13 more
```

im sorry but it also has this problem

**Comment by Yurinann** [comment]
```
[20:10:24 WARN]: Exception in thread "Craft Scheduler Thread - 6" org.apache.commons.lang.UnhandledException: Plugin DailyRewards v1.5.1 generated an exception while executing task 19
[20:10:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[20:10:24 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[20:10:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:10:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:10:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:10:24 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class cz.revivalo.dailyrewards.configuration.enums.Config
[20:10:24 WARN]:        at cz.revivalo.dailyrewards.DailyRewards.lambda$onEnable$0(DailyRewards.java:57)
[20:10:24 WARN]:        at cz.revivalo.dailyrewards.updatechecker.UpdateChecker.lambda$getVersion$0(UpdateChecker.java:28)
[20:10:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[20:10:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[20:10:24 WARN]:        ... 4 more
```

another error, maybe package problem?

**Comment by Revivalo** [comment]
Fixed in latest version on https://www.spigotmc.org/resources/%E2%9A%A1-daily-weekly-monthly-rewards-mysql-hex-colors-support-1-8-1-19-3.81780/
